=== shinevue/game-backend/artifacts/module_schema.json
{"type":"object","properties":{"status":{"enum":["beta","end_of_life","maintenance","preview","stable"],"type":"string"},"name":{"description":"The human readable name of the module.","type":"string"},"description":{"description":"A short description of the module.","type":"string"},"icon":{"description":"The [Font Awesome](https://fontawesome.com/icons) icon name of the module.","type":"string"},"tags":{"description":"The tags associated with this module.","type":"array","items":{"type":"string"}},"authors":{"description":"The GitHub handle of the authors of the module.","type":"array","items":{"type":"string"}},"scripts":{"type":"object","additionalProperties":{"$ref":"#/definitions/ScriptConfig"}},"actors":{"type":"object","additionalProperties":{"$ref":"#/definitions/ActorConfig"}},"errors":{"type":"object","additionalProperties":{"$ref":"#/definitions/ErrorConfig"}},"dependencies":{"type":"object","additionalProperties":{"$ref":"#/definitions/DependencyConfig"}},"defaultConfig":{"description":"Default user config.\n\nThe user-provided config will be deep merged with this config."}},"additionalProperties":false,"required":["errors","scripts"],"definitions":{"ScriptConfig":{"type":"object","properties":{"name":{"description":"The human readable name of the script.","type":"string"},"description":{"description":"A short description of the script.","type":"string"},"public":{"description":"If the script can be called from the public HTTP interface.\n\nIf enabled, ensure that authentication & rate limits are configured for\nthis endpoints. See the `user` and `rate_limit` modules.","default":false,"type":"boolean"}},"additionalProperties":false},"ActorConfig":{"type":"object","properties":{"storage_id":{"description":"A globally unique string for storing data for this actor.\n\n**IMPORTANT** Changing this will effectively unlink all data stored in this actor. Changing it back to\nthe old value will restore the data.","type":"string"}},"additionalProperties":false,"required":["storage_id"]},"ErrorConfig":{"type":"object","properties":{"name":{"description":"The human readable name of the error.","type":"string"},"description":{"description":"A short description of the error.","type":"string"}},"additionalProperties":false},"DependencyConfig":{"type":"object","additionalProperties":false}},"$schema":"http://json-schema.org/draft-07/schema#"}

=== shinevue/game-backend/tests/basic/modules/foo/module.json
{
	"status": "preview",
	"authors": [
		"NathanFlurry"
	],
	"scripts": {
		"ping": {
			"public": true
		},
		"create_entry": {
			"public": true
		},
		"call_self": {
			"public": true
		},
		"actor": {
			"public": true
		}
	},
	"actors": {
		"ponger": {
			"storage_id": "foobar"
		}
	},
	"errors": {
		"db_error": {}
	}
}
